//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IFewestConnections")]
    public interface IFewestConnections {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFewestConnections/calculate", ReplyAction="http://tempuri.org/IFewestConnections/calculateResponse")]
        string calculate(string airport1, string airport2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFewestConnections/calculate", ReplyAction="http://tempuri.org/IFewestConnections/calculateResponse")]
        System.Threading.Tasks.Task<string> calculateAsync(string airport1, string airport2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFewestConnectionsChannel : WindowsFormsApp1.ServiceReference2.IFewestConnections, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FewestConnectionsClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference2.IFewestConnections>, WindowsFormsApp1.ServiceReference2.IFewestConnections {
        
        public FewestConnectionsClient() {
        }
        
        public FewestConnectionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FewestConnectionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FewestConnectionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FewestConnectionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string calculate(string airport1, string airport2) {
            return base.Channel.calculate(airport1, airport2);
        }
        
        public System.Threading.Tasks.Task<string> calculateAsync(string airport1, string airport2) {
            return base.Channel.calculateAsync(airport1, airport2);
        }
    }
}
